# Generated by Django 4.2.2 on 2023-06-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
